# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'

alias src='cd $HOME/src'
alias ws='cd $HOME/src/workspace'
# keeping Debian up to date
alias update='sudo apt-get update'
alias upgrade='sudo apt-get upgrade'
alias up="sudo apt-get update && sudo apt-get upgrade --yes && sudo apt-get dist-upgrade --yes && sudo apt-get autoclean --yes && sudo apt-get autoremove --yes"

alias tmux="TERM=screen-256color-bce tmux"
alias mux="TERM=screen-256color-bce mux"
